# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Envoy-Coffee' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Envoy-Coffee
  pod 'Kingfisher', '~> 5.0'

  target 'Envoy-CoffeeTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Envoy-CoffeeUITests' do
    # Pods for testing
  end

end
